// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjUJItLlz7pkkykmHMuvHMxUYajFdTrUg',
    appId: '1:1082284537213:web:33aa3c25098099f4354814',
    messagingSenderId: '1082284537213',
    projectId: 'reminder-app-b0262',
    authDomain: 'reminder-app-b0262.firebaseapp.com',
    storageBucket: 'reminder-app-b0262.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEDNpg00K8mtz-FAYPmerSRBn4E02JMp8',
    appId: '1:1082284537213:android:e9b6ed26a78ca0d4354814',
    messagingSenderId: '1082284537213',
    projectId: 'reminder-app-b0262',
    storageBucket: 'reminder-app-b0262.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBdMyNlHlfLr6FU8GHwWIh9G36c904bLk',
    appId: '1:1082284537213:ios:81756529e5867351354814',
    messagingSenderId: '1082284537213',
    projectId: 'reminder-app-b0262',
    storageBucket: 'reminder-app-b0262.appspot.com',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBdMyNlHlfLr6FU8GHwWIh9G36c904bLk',
    appId: '1:1082284537213:ios:aae76cb45e994c75354814',
    messagingSenderId: '1082284537213',
    projectId: 'reminder-app-b0262',
    storageBucket: 'reminder-app-b0262.appspot.com',
    iosBundleId: 'com.example.reminderApp.RunnerTests',
  );
}
